- name: variables
  hosts: local
  connection: local
  vars: # PLAY level variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Sivakumar
  tasks:
  - name: print the variables
    vars: # Tast level variables
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER}}"

  - name: print the variables1
    ansibleansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"